apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/AyushRaturi/Ai-task-platform.git
    targetRevision: develop
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
