apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-task-platform-staging

resources:
  - ../../base

namePrefix: ""

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: worker
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
    target:
      kind: HorizontalPodAutoscaler
      name: worker-hpa

images:
  - name: ayushraturi/ai-app-backend
    newTag: latest
  - name: ayushraturi/ai-app-frontend
    newTag: latest
  - name: ayushraturi/ai-app-worker
    newTag: latest
